In [3]:
pip install imutils

  Stored in directory: /root/.cache/pip/wheels/db/23/45/fc7424906880ffa9577a2a428b961f2b79e0e21d9f71e7e6bc
Successfully built imutils
You should consider upgrading via the 'pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [4]:
# import the necessary packages
from imutils.video import VideoStream
from imutils.video import FPS
import imutils
import time
import cv2
import os
import errno

In [7]:
#path='./Abhishek/faceforensics/original_sequences/youtube/c23/videos'
path='./Abhishek/faceforensics/manipulated_sequences/NeuralTextures/c23/videos/'
path_to_copy='./Sayali/FF_preprocessed_Sayali_Fake/'
count=0
for videos in os.listdir(path_to_copy):
    a=0
    p=os.path.join(path_to_copy,videos)
    num_files = len([f for f in os.listdir(p)if os.path.isfile(os.path.join(p, f))])
    
    x=os.path.join(path,videos)
    cap = cv2.VideoCapture(x)
    length = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    if length!=0:
        a=num_files/length
    if a<.8:
        count=count+1
count

13

In [2]:
def valid_x(x,a):
    if x-a>=0:
        return x-a
    else:
        return 0

def valid_y(y,a):
    if y-a>=0:
        return y-a
    else:
        return 0

def valid_w(x,w,a,width):
    if x+w+2*a<=width:
        return w+2*a
    else:
        return width-x

def valid_h(y,h,a,height):
    if y+h+2*a<=height:
        return h+2*a
    else:
        return height-h


In [4]:
def detect_faces(cascade, test_image,height,width, scaleFactor = 1.3):
    # create a copy of the image to prevent any changes to the original one.
    image_copy = test_image.copy()

    #convert the test image to gray scale as opencv face detector expects gray images
    gray_image = cv2.cvtColor(image_copy, cv2.COLOR_BGR2GRAY)

    # Applying the haar classifier to detect faces
    faces_rect = cascade.detectMultiScale(gray_image, scaleFactor=scaleFactor, minNeighbors=5)
    print(faces_rect)
    n=0
    l=[]
    for (x, y, w, h) in faces_rect:
        if w>n:
            n=w
            l=[x,y,w,h]
    if(l==[]):
      return
    a=0.1*l[2]
    x1=valid_x(l[0],a)
    y1=valid_y(l[1],a)
    w1=valid_w(x1,l[2],a,width)
    h1=valid_h(y1,l[3],a,height)
    return (int(x1),int(y1),int(w1),int(h1))

In [5]:
path='./Abhishek/faceforensics/manipulated_sequences/NeuralTextures/c23/videos'
path_to_copy='./Sayali/FF_preprocessed_Sayali_Fake'

In [ ]:


OPENCV_OBJECT_TRACKERS = {
    "csrt":cv2.TrackerCSRT_create,
    "kcf":cv2.TrackerKCF_create,
}

haar_cascade_face=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

for videos in os.listdir(path):
  tracker = OPENCV_OBJECT_TRACKERS["kcf"]()

  #for bounding box cordinates of obj we are going
  initBB = None
  print(videos)
  p=os.path.join(path,videos)
  to_copy=os.path.join(path_to_copy,videos)
  try:
    os.mkdir(to_copy)
  except OSError as e:
    if e.errno == errno.EEXIST:
        print('Directory not created.')
        continue
    else:
        raise
  print(to_copy)
  vs = cv2.VideoCapture(p)
  #loop over frames from the video stream
  flag = False
  count=0
  while True:
      if count>1000:
          break
      ret,frame = vs.read()

      if frame is None:
          continue
      if ret is False:
          continue
            
      (H, W) = frame.shape[:2]


      #we are curently tracking on object
      if initBB is not None:
          (success, box) = tracker.update(frame)
          #if the tracking was a success
          if ret and success:
            (x, y, w, h) = [int(v) for v in box]
            #cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 2)
            a=frame[y:y+h,x:x+w]
            if(a.size>0):
              cv2.imwrite(to_copy+'/'+str(count)+'.jpg',a)

          #update the fps counter
          fps.update()
          fps.stop()

          info = [
              ("Tracker", "kcf"),
              ("Success", "Yes" if success else "No"),
              ("FPS", "{:.2f}".format(fps.fps())),
          ]
          
          for (i, (k, v)) in enumerate(info):
              text = "{}: {}".format(k, v)
              cv2.putText(frame, text, (10, H - ((i * 20) + 20)),
                  cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 255), 2)

      #show the output frame
      key = cv2.waitKey(1) & 0xFF

      #we are selecting the bounding box so press "s" and click enter or space
      #if you want again reselect then press escape
      count=count+1
      if flag==False:
          initBB = detect_faces(haar_cascade_face, frame,H,W)
          if(initBB==None):
            continue
          print(initBB)
          flag = True
          tracker.init(frame, initBB)
          fps = FPS().start()

      elif key == ord("q"):
          break

631_551.mp4
Directory not created.
531_549.mp4
Directory not created.
852_834.mp4
Directory not created.
975_978.mp4
./Sayali/FF_preprocessed_Sayali_Fake/975_978.mp4
[[560 181 207 207]]
(539, 160, 248, 248)


# Start from here

In [2]:
!pip install imutils opencv-contrib-python

     |████████████████████████████████| 66.7 MB 5.4 MB/s eta 0:00:013
  Created wheel for imutils: filename=imutils-0.5.4-py3-none-any.whl size=25858 sha256=6cc3eef4e9a50cd9cb10b33088d77018413499d3650a3b2f27707d05bf1ac5fa
  Stored in directory: /root/.cache/pip/wheels/f5/0c/3a/61b992f7aa85de40f339e6d4970d91dddb103dd0ad6c5d58f2
Successfully built imutils
You should consider upgrading via the '/usr/bin/python -m pip install --upgrade pip' command.


In [3]:

# import the necessary packages
from imutils.video import VideoStream
from imutils.video import FPS
import imutils
import time
import cv2
import os
import errno

os.listdir()

def valid_x(x,a):
    if x-a>=0:
        return x-a
    else:
        return 0

def valid_y(y,a):
    if y-a>=0:
        return y-a
    else:
        return 0

def valid_w(x,w,a,width):
    if x+w+2*a<=width:
        return w+2*a
    else:
        return width-x

def valid_h(y,h,a,height):
    if y+h+2*a<=height:
        return h+2*a
    else:
        return height-h


def detect_faces(cascade, test_image,height,width, scaleFactor = 1.3):
    # create a copy of the image to prevent any changes to the original one.
    image_copy = test_image.copy()

    #convert the test image to gray scale as opencv face detector expects gray images
    gray_image = cv2.cvtColor(image_copy, cv2.COLOR_BGR2GRAY)

    # Applying the haar classifier to detect faces
    faces_rect = cascade.detectMultiScale(gray_image, scaleFactor=scaleFactor, minNeighbors=5)
    print(faces_rect)
    n=0
    l=[]
    for (x, y, w, h) in faces_rect:
        if w>n:
            n=w
            l=[x,y,w,h]
    if(l==[]):
      return
    a=0.1*l[2]
    x1=valid_x(l[0],a)
    y1=valid_y(l[1],a)
    w1=valid_w(x1,l[2],a,width)
    h1=valid_h(y1,l[3],a,height)
    return (int(x1),int(y1),int(w1),int(h1))


In [3]:
pip install opencv-contrib-python

You should consider upgrading via the '/usr/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [7]:

path='./Abhishek/faceforensics/original_sequences/youtube/c23/videos'
path_to_copy='./Sayali/Time_analysis_real'

OPENCV_OBJECT_TRACKERS = {
    "csrt":cv2.TrackerCSRT_create,
    "kcf":cv2.TrackerKCF_create,
    "boosting": cv2.TrackerBoosting_create,
    "mil": cv2.TrackerMIL_create,
    "tld": cv2.TrackerTLD_create,
    "medianflow": cv2.TrackerMedianFlow_create,
    "mosse": cv2.TrackerMOSSE_create
}

haar_cascade_face=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

AttributeError: module 'cv2' has no attribute 'TrackerCSRT_create'

In [3]:
from random import sample
list1 = os.listdir(path)
v=sample(list1,20)
v



['377.mp4',
 '172.mp4',
 '284.mp4',
 '180.mp4',
 '024.mp4',
 '168.mp4',
 '553.mp4',
 '890.mp4',
 '690.mp4',
 '295.mp4',
 '778.mp4',
 '893.mp4',
 '067.mp4',
 '246.mp4',
 '584.mp4',
 '002.mp4',
 '560.mp4',
 '994.mp4',
 '423.mp4',
 '460.mp4']

In [84]:
import time

t=0
f=0

fr_count=0

for videos in v:
    
    tracker = OPENCV_OBJECT_TRACKERS["tld"]()
    
    #for bounding box cordinates of obj we are going
    initBB = None
    print(videos)
    p=os.path.join(path,videos)
#     to_copy=os.path.join(path_to_copy,videos)

#     try:
#         os.mkdir(to_copy)
#     except OSError as e:
#         if e.errno == errno.EEXIST:
#             print('Directory not created.')
#             continue
#         else:
#             raise
#     print(to_copy)
    
    vs = cv2.VideoCapture(p)
    #loop over frames from the video stream
    flag = False
    count=0
    e=0
    while True:
        
        if count>1000:
            break
      
        ret,frame = vs.read()
        
        if frame is None:
            break
        if ret is False:
            break
            
        (H, W) = frame.shape[:2]
        
        #we are curently tracking on object
        
        if initBB is not None:
            start=time.time()
            (success, box) = tracker.update(frame)
            end=time.time()
            t=t+(end-start)
            #if the tracking was a success
            if ret and success:
                (x, y, w, h) = [int(v) for v in box]
                #cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 2)
                a=frame[y:y+h,x:x+w]
                if(a.size>0):
                    e=e+1

            #update the fps counter
            
            fps.update()
            fps.stop()

#             info = [
#                 ("Tracker", "kcf"),
#                 ("Success", "Yes" if success else "No"),
#                 ("FPS", "{:.2f}".format(fps.fps())),
#             ]

            #for (i, (k, v)) in enumerate(info):
                #text = "{}: {}".format(k, v)
                #cv2.putText(frame, text, (10, H - ((i * 20) + 20)),
                    #cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 255), 2)

        #we are selecting the bounding box so press "s" and click enter or space
        #if you want again reselect then press escape
        count=count+1
        if flag==False:
            initBB = detect_faces(haar_cascade_face, frame,H,W)
            if(initBB==None):
                continue
            print(initBB)
            flag = True
            tracker.init(frame, initBB)
            fps = FPS().start()
    fr_count=fr_count+e
    f=f+count
    
print("Total time required:")
print(t)
print("total frames:")
print(f)
print("total faces detected:")
print(fr_count)
print("Success Rate:")
print(fr_count/9537)
print("Time per frame:")
print(t/9537)

777.mp4
[[238  90 177 177]]
(220, 72, 212, 212)
033.mp4
[[368  55  76  76]
 [134 194  49  49]]
(360, 47, 91, 91)
314.mp4
[[152 109 180 180]]
(134, 91, 216, 216)
737.mp4
[[207  66 116 116]]
(195, 54, 139, 139)
255.mp4
[[548 128 277 277]]
(520, 100, 332, 332)
539.mp4
[[121  53 249 249]]
(96, 28, 298, 298)
545.mp4
[[292 142 216 216]]
(270, 120, 259, 259)
321.mp4
[[285 106  93  93]]
(275, 96, 111, 111)
791.mp4
[[350  96 174 174]]
(332, 78, 208, 208)
422.mp4
[[911 327 513 513]]
(859, 275, 615, 615)
349.mp4
[[789  74 137 137]]
(775, 60, 164, 164)
260.mp4
[[139 132 176 176]]
(121, 114, 211, 211)
574.mp4
()
[[212 121 134 134]]
(198, 107, 160, 160)
363.mp4
[[313  96 116 116]]
(301, 84, 139, 139)
608.mp4
[[240  57 148 148]]
(225, 42, 177, 177)
874.mp4
[[804 300 397 397]]
(764, 260, 476, 476)
632.mp4
[[722 172 346 346]]
(687, 137, 415, 415)
754.mp4
[[449 122 224 224]]
(426, 99, 268, 268)
793.mp4
[[460 106 274 274]]
(432, 78, 328, 328)
900.mp4
[[270 135 128 128]]
(257, 122, 153, 153)
Total time re

# For Haar Cascades

In [85]:
import cv2
import sys
import imutils
import numpy as np
c='./Abhishek/faceforensics/original_sequences/youtube/c23/videos/722.mp4'
# Load the Haar Cascade
cascPath = 'haarcascade_frontalface_default.xml'

# Create the Haar Cascade
faceCascade = cv2.CascadeClassifier(cascPath)
v=['777.mp4',
 '033.mp4',
 '314.mp4',
 '737.mp4',
 '255.mp4',
 '539.mp4',
 '545.mp4',
 '321.mp4',
 '791.mp4',
 '422.mp4',
 '349.mp4',
 '260.mp4',
 '574.mp4',
 '363.mp4',
 '608.mp4',
 '874.mp4',
 '632.mp4',
 '754.mp4',
 '793.mp4',
 '900.mp4']

print(v)
t=0
f=0
fr_count=0;
for videos in v:
    print(videos)
    p=os.path.join(path,videos)
    # Read the Video
    
    video_capture = cv2.VideoCapture(p)
    count=0
    while True:
        # Capture frame-by-frame
        #count=count+1
        ret, frame = video_capture.read()
        if frame is None:
            break
        if ret is False:
            break
        (H, W) = frame.shape[:2]
        if np.shape(frame) == ():
            break
        count=count+1
        #print(count)
        # Resize the Frame to improve speed
        #frame = imutils.resize(frame, width=450)
    
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        t1=time.time()
        faces = faceCascade.detectMultiScale(
            gray,
            scaleFactor=1.3,
            minNeighbors=5,
        )
        t2=time.time()
        t=t+(t2-t1)
        n=0
        for (x, y, w, h) in faces:
            if w>n:
                n=w
                l=[x,y,w,h]
                
        a=0.1*l[2]
        x=int(valid_x(l[0],a))
        y=int(valid_y(l[1],a))
        w=int(valid_w(x,l[2],a,W))
        h=int(valid_h(y,l[3],a,H))
        a=gray[y:y+h,x:x+w]
        if a.size>0:
            fr_count=fr_count+1
            
        # Draw a rectangle around the Faces
        #for (x, y, w, h) in faces:
            #cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)

        # Display the resulting Frame
        #cv2.imshow('Video', frame)
    
    f=f+count
        
        


print("Total time required:")
print(t)
print("total frames:")
print(f)
print("Total faces detected successfully:")
print(fr_count)
print("Success rate:")
print(fr_count/f)

['777.mp4', '033.mp4', '314.mp4', '737.mp4', '255.mp4', '539.mp4', '545.mp4', '321.mp4', '791.mp4', '422.mp4', '349.mp4', '260.mp4', '574.mp4', '363.mp4', '608.mp4', '874.mp4', '632.mp4', '754.mp4', '793.mp4', '900.mp4']
777.mp4
033.mp4
314.mp4
737.mp4
255.mp4
539.mp4
545.mp4
321.mp4
791.mp4
422.mp4
349.mp4
260.mp4
574.mp4
363.mp4
608.mp4
874.mp4
632.mp4
754.mp4
793.mp4
900.mp4
Total time required:
142.09819078445435
total frames:
9537
Total faces detected successfully:
9537
Success rate:
1.0


In [86]:
print("For Haar Cascades:")
print("Total frames:")
print(f)
print("Total time required:")
print(t)
print("Time per frame:")
print(t/f)

For Haar Cascades:
Total frames:
9537
Total time required:
142.09819078445435
Time per frame:
0.014899673983900005


In [50]:
v=['777.mp4',
 '033.mp4',
 '314.mp4',
 '737.mp4',
 '255.mp4',
 '539.mp4',
 '545.mp4',
 '321.mp4',
 '791.mp4',
 '422.mp4',
 '349.mp4',
 '260.mp4',
 '574.mp4',
 '363.mp4',
 '608.mp4',
 '874.mp4',
 '632.mp4',
 '754.mp4',
 '793.mp4',
 '900.mp4']
import cv2
total=0
for videos in v:
    p=os.path.join(path,videos)
    cap = cv2.VideoCapture(p)
    length = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    total=total+length
total

9537